volumes:
  postgresql-data:

services:
  bankcards-app:
    build: .
    env_file:
      - .env
    ports:
      - "8182:8182"
    depends_on:
      - bankcards-db
    container_name: bankcards-app
  bankcards-db:
    image: postgres:17-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - PGPORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: bankcards-db