volumes:
  postgresql-data:
  caddy_data:
  caddy_config:

services:
  bankcards-app:
    build: .
    env_file:
      - .env
    expose:
      - 8080
    depends_on:
      - bankcards-db
    container_name: bankcards-app
    networks:
      - backend

  bankcards-db:
    image: postgres:17-alpine
    container_name: bankcards-db
    env_file:
      - .env
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - backend

  caddy:
    image: caddy:2.10.2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - bankcards-app
    networks:
      - backend

networks:
  backend:
