server:
  port: 8080

spring:
  application:
    name: bankcards
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-root.yml

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

credentials:
  admin:
    first-name: ${ADMIN_FIRST_NAME}
    last-name: ${ADMIN_LAST_NAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

logging:
  level:
    root: info